name: firesafe_vnex
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+4

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  go_router: ^10.1.2
  shared_preferences: ^2.2.1
  easy_localization: ^3.0.3
  json_annotation: ^4.8.1
  build_runner: ^2.4.6
  logger: ^2.0.2+1
  equatable: ^2.0.5
  flutter_svg: ^2.0.9
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  fluttertoast: ^8.2.4
  animations: ^2.0.11
  dio: ^5.4.0
  flutter_dotenv: ^5.1.0
  file_picker: ^6.1.1
  flutter_spinkit: ^5.2.0
  readmore: ^2.2.0
  shimmer: ^3.0.0
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  flutter_html: ^3.0.0-beta.2
  m3_carousel: ^1.0.2
  cached_network_image: ^3.3.1
  sqflite: ^2.3.2
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/features/
    - assets/images/product-categories/
    - assets/translations/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf
    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist.ttf
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans.ttf
